import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout"


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
   weight: '500',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <ClientLayout>  
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}